# -*- coding: utf-8 -*-
"""soal1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtZTROVwihOwvQSDc-_nqBl2l_pFG_im
"""

def deteksi_hama(gejala):
  # Fungsi ini berfungsi untuk mengidentifikasi jenis hama berdasarkan kombinasi gejala yang diberikan
  # Logika yang digunakan adalah percabangan if-elif, yang mengaitkan setiap kombinasi gejala dengan jenis hama tertentu
  # Jika tidak ada kombinasi gejala yang cocok, hasilnya akan dikembalikan sebagai "Hama tidak diketahui"

    if "daun menguning" in gejala and "buah busuk" in gejala:
        return "Bakteri Pembusuk Buah" # Aturan 1
    elif "daun berlubang" in gejala and "tanaman layu" in gejala:
        return "Ulat" #Aturan 2
    elif "bercak hitam" in gejala and "daun berlubang" in gejala:
        return "Jamur Bercak Daun" #Aturan 3
    elif "buah busuk" in gejala and "daun rontok" in gejala:
        return "Jamur Busuk Buah" #Aturan 4
    elif "daun menguning" in gejala and "bercak hitam" in gejala:
        return "Virus Tanaman" #Aturan 5
    if "daun menguning" in gejala and "tanaman layu" in gejala:
        return "Kutu Daun" #Aturan 6
    else:
      # Fungsi akan mengembalikan hasil default jika kombinasi gejala tidak ditemukan dalam daftar.
        return "Hama tidak diketahui"


gejala_input = ["daun berlubang", "tanaman layu"] # List ini berisi gejala yang diamati dari tanaman
# Pada kasus ini, input gejala sesuai dengan kondisi "Ulat"
hasil = deteksi_hama(gejala_input)
print("Jenis hama:", hasil) # Output menunjukkan jenis hama yang terdeteksi sesuai input